[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE App"
documentation = "https://docs.rs/safe_app"
homepage = "https://maidsafe.net"
license = "MIT OR BSD-3-Clause"
name = "safe_app"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.9.0"
build = "build.rs"
edition = "2018"

[dependencies]
config_file_handler = "~0.11.0"
ffi_utils = "~0.11.0"
futures = "~0.1.17"
log = "~0.4.1"
lru-cache = "~0.1.1"
maidsafe_utilities = "~0.16.0"
rand = "~0.3.18"
routing = "~0.37.0"
rust_sodium = "~0.10.0"
serde = "~1.0.27"
serde_derive = "~1.0.27"
safe_authenticator = { path = "../safe_authenticator", version = "~0.9.0", optional = true }
safe_core = { path = "../safe_core", version = "~0.32.0" }
self_encryption = "~0.13.0"
tiny-keccak = "~1.3.1"
tokio-core = "~0.1.17"
unwrap = "~1.2.0"
jni = { version = "~0.10.2", optional = true }

[dev-dependencies]
clap = "=2.25.1"

[dev-dependencies.safe_authenticator]
path = "../safe_authenticator"
version = "~0.9.0"
features = ["testing"]

[dev-dependencies.safe_core]
path = "../safe_core"
version = "~0.32.0"
features = ["testing"]

[build-dependencies]
ffi_utils = "~0.11.0"
jni = "~0.10.1"
routing = "~0.37.0"
rust_sodium = "~0.10.0"
safe_bindgen = "~0.11.0"
unwrap = "~1.2.0"

[features]
use-mock-routing = ["testing", "safe_core/use-mock-routing", "safe_authenticator/use-mock-routing"]
testing = ["safe_core/testing", "safe_authenticator/testing"]
bindings = []

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]

[[example]]
bench = false
name = "client_stress_test"

[[example]]
bench = false
name = "gen_invites"

[[example]]
bench = false
name = "self_authentication"
